# Generated by Django 4.2 on 2025-04-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnCourseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_course_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=50, null=True)),
                ('degree_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_degree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitutionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnLocationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_location_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnSelectedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_selected_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_stream',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnStreamChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_stream_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('hsc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_gender', models.CharField(max_length=20)),
                ('school_passed_out_year', models.IntegerField()),
                ('studied_institution_type', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('stream', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wn_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WnInstitutionCourse',
            fields=[
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recommender.wninstitution')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution_course',
                'managed': False,
            },
        ),
    ]
