# Generated by Django 5.1.7 on 2025-03-27 10:50

import recommendations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WnTextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Course'), ('institution', 'Institution'), ('user', 'User Profile')], help_text='Type of content this embedding represents', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related object in its table')),
                ('text_hash', models.CharField(db_index=True, help_text='SHA256 hash of the original text for change detection', max_length=64)),
                ('original_text_length', models.PositiveIntegerField(help_text='Character length of original text')),
                ('embedding', models.JSONField(encoder=recommendations.models.NPArrayEncoder, help_text='Vector embedding stored as JSON array')),
                ('embedding_version', models.CharField(default='all-MiniLM-L6-v2', help_text='Model version used to generate embedding', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text Embedding',
                'verbose_name_plural': 'Text Embeddings',
                'db_table': 'wn_text_embedding',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='wn_text_emb_content_877157_idx'), models.Index(fields=['text_hash'], name='wn_text_emb_text_ha_6dc4f2_idx'), models.Index(fields=['embedding_version'], name='wn_text_emb_embeddi_2200e8_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
