# Generated by Django 4.2 on 2025-03-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WnDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('hsc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_gender', models.CharField(max_length=20)),
                ('school_passed_out_year', models.IntegerField(default=None, null=True)),
                ('studied_institution_type', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('stream', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wn_user',
                'managed': False,
            },
        ),
    ]
