# Generated by Django 4.2 on 2025-02-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wnuser',
            options={},
        ),
    ]
