# Generated by Django 4.2 on 2025-02-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_description', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnCourseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_course_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=50, null=True)),
                ('degree_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_degree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitutionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnLocationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_location_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnSelectedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_selected_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_stream',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnStreamChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_stream_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WnInstitutionCourse',
            fields=[
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='institutions.wninstitution')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'wn_institution_course',
                'managed': False,
            },
        ),
    ]
