# Generated by Django 4.2 on 2025-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WnFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'wn_favourite',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='wncontact',
            options={'managed': False},
        ),
    ]
